name: Fly Deploy

on:
  workflow_run:
    workflows: ["Lint and Tests"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    name: Deploy app
    permissions:
      contents: read
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
